  name: Setup Android Dependencies

  runs:
    using: composite
    steps:
    - name: Setup JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: zulu
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      with:
        cache-read-only: false
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      with:
        cmdline-tools-version: latest
        accept-android-sdk-licenses: true